# MySQL Configuration
spring.datasource.url=jdbc:mysql://172.21.162.143:3306/cms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=QgeUffUwYKnecSqrv3FrGPFs
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://root:DJAZWoOSoAIQSiqHL37Wg89f@172.21.45.95:27017/prescriptions?authSource=admin
